In [41]:
#Python for Data Science
#1-D array

import numpy as np
list=[1,2,3,4,5]
sample_array=np.array(list)
print("List in Python: ",list)
print("Numpy array in python: ",sample_array)

List in Python:  [1, 2, 3, 4, 5]
Numpy array in python:  [1 2 3 4 5]


In [42]:
#2-D array

arr=np.array([[1,2,3,3],[4,5,5,6],[7,8,9,10]])
print(arr)

[[ 1  2  3  3]
 [ 4  5  5  6]
 [ 7  8  9 10]]


In [43]:
#Slicing and Indexing

import numpy as np
list=[1,2,3,4,5]
l1=np.array(list)
print("Accessing the elements: ",l1)

print("Single element: ",l1[0])

print("Range of elements: ",l1[0:2])

print("Range with step count: ",l1[::2])

l1[0]=2
print("Modifying array: ",l1)

Accessing the elements:  [1 2 3 4 5]
Single element:  1
Range of elements:  [1 2]
Range with step count:  [1 3 5]
Modifying array:  [2 2 3 4 5]


In [44]:
list2=[[1,2],[3,4],[5,6]]
l2=np.array(list2)
print("Accessing the elements: \n",l2)

print("Single element: ",l2[0],l2[0,1])

print("Range of elements: \n",l2[0:2])

print("Range with step count: \n",l2[::2])

l2[0]=[4,5]
print("Modifying array: \n",l2)

Accessing the elements: 
 [[1 2]
 [3 4]
 [5 6]]
Single element:  [1 2] 2
Range of elements: 
 [[1 2]
 [3 4]]
Range with step count: 
 [[1 2]
 [5 6]]
Modifying array: 
 [[4 5]
 [3 4]
 [5 6]]


In [45]:
l2=np.array([[1,2],[3,4]])
l2

array([[1, 2],
       [3, 4]])

In [46]:
#Reshaping

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print("Shape of array:" ,arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape of array: (2, 4)


In [47]:
#Reshape from 1-D to 2-D

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
#Reshape from 1-D to 3-D

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [49]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [50]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(6,2,1) #6blocks,2rows,1columns
print(newarr)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]]


In [51]:
#Flattening the arrays: 

import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
newarr=arr.reshape(-1)
print("Reshaping the array: \n",newarr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Reshaping the array: 
 [1 2 3 4 5 6 1 2 3 4 5 6]


In [52]:
#Inbuilt functions

#sort()

a=np.array([1,3,3,4,0])

np.sort(a)


array([0, 1, 3, 3, 4])

In [53]:
a=np.array([1,2,3,4])
b=np.array([3,2,3,4])
np.concatenate((a,b))


array([1, 2, 3, 4, 3, 2, 3, 4])

In [54]:
import numpy as np

a=np.zeros(10,dtype=int)
print(a)
b = np.zeros((2,), dtype=[('x', 'float'), ('y', 'int')])
print(b)


[0 0 0 0 0 0 0 0 0 0]
[(0., 0) (0., 0)]


In [55]:
a=np.append(a,[7])
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7])

In [56]:
#search

import numpy as np

arr=np.array([1,2,3,4])
x=np.where(arr==4) #use for searching an element
print(x)


(array([3]),)


In [57]:
#sum()
print(np.sum(arr))

10


In [58]:

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

res=arr.sum(axis = 1)
print(res)


[10 26 42]


In [59]:
#arrange

np.arange(3)

array([0, 1, 2])

In [60]:
import numpy as np
array = np.array([[1, 2, 3],[11, 22, 33],[4, 5, 6], [8, 9, 10], [20, 30, 40]])

# calculating sum along axis=1 i.e row0wise
output = array.sum(axis = 1)
print("\n\nSum row-wise: ", output)




Sum row-wise:  [ 6 66 15 27 90]


In [61]:
import numpy as np
array = np.array([[1, 2, 3],[11, 22, 33],[4, 5, 6], [8, 9, 10], [20, 30, 40]])

# calculating sum along axis=0 i.e column0wise
output = array.sum(axis = 0)
print("\n\nSum row-wise: ", output)



Sum row-wise:  [44 68 92]


Arithmetic Functions

In [62]:
arr1=np.array([10,11,12,13,14,15])
arr2=np.array([20,21,22,23,24,25])

newarr=np.add(arr1,arr2)

print(newarr)

[30 32 34 36 38 40]


In [63]:
#power of numbers where array two elements are powers for array one elements..
import numpy as np
a1=np.array([2,3,4])
b1=np.array([4,5,6])
c1=np.power(a1,b1)
print(c1)

[  16  243 4096]


In [64]:
#sqrt-square root
arr1=([2,5,9])
a=np.sqrt(arr1)
a

array([1.41421356, 2.23606798, 3.        ])

In [65]:
import numpy as np

arr1=([9,8,7,6,5,4,3,2])
arr2=([20,19,18,17,16,15,14,13])

addi=np.add(arr1,arr2)
print('\nAdditon : ',addi)

subt=np.subtract(arr1,arr2)
print('\nSubtraction : ',subt)

multi=np.multiply(arr1,arr2)
print('\n Multiplication : ',multi)

div=np.divide(arr1,arr2)
print('\n Division : ',div)


Additon :  [29 27 25 23 21 19 17 15]

Subtraction :  [-11 -11 -11 -11 -11 -11 -11 -11]

 Multiplication :  [180 152 126 102  80  60  42  26]

 Division :  [0.45       0.42105263 0.38888889 0.35294118 0.3125     0.26666667
 0.21428571 0.15384615]


In [66]:
new_arr=([1,2,3])
new_arr2=([4,5,6])
#new_arr3=([7,8,9])

print(np.add(new_arr,new_arr2))
print(np.subtract(new_arr,new_arr2))
print(np.multiply(new_arr,new_arr2))
print(np.divide(new_arr,new_arr2))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [67]:
#Arithmetic Functions on 3 x 3 matrix 

arr_new=([[1,2,3],[4,5,6],[7,8,9]])
new_arr=([[4,5,6],[7,8,9],[1,2,3]])
print('Additon of 3 x 3 :\n',np.add(arr_new,new_arr))
print('\nSubtraction of 3 x 3 : \n',np.subtract(arr_new,new_arr))
print('\nMultiply of 3 x 3 : \n',np.multiply(arr_new,new_arr))
print('\nDivision of 3 x 3 : \n',np.divide(arr_new,new_arr))

Additon of 3 x 3 :
 [[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]

Subtraction of 3 x 3 : 
 [[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]

Multiply of 3 x 3 : 
 [[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]

Division of 3 x 3 : 
 [[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]


In [68]:
array=([[1,2,3],[4,5,6],[7,8,9]])

for i in range(len(array)):
    x+=np.sum(array[i])
    print(x)

[[9]]
[[24]]
[[48]]


Statistical Function

In [69]:
arr=np.array([1,2,3,4,5,6])

a=np.amin(arr)
print(a)

b=np.amax(arr)
print(b)

c=np.ptp(arr)
print(c)

d=np.percentile(arr,3)
print(d)

e=np.median(arr)
print(e)

f=np.mean(arr)
print(f)

g=np.std(arr)
print(g)

h=np.var(arr)
print(h)

1
6
5
1.15
3.5
3.5
1.707825127659933
2.9166666666666665


Universal Function

In [70]:
# Creation of user defined 'universal functions'

import numpy as np

def myunif(x,y):
    return x+y

myunif=np.frompyfunc(myunif,2,1) #myunif=array name, 2=no of i/p, 1= no of o/p 

#frompyfunc used to add the user-defined function as universal function in Numpy Library.. 

print(myunif([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


In [71]:
# Create your own ufunc pow() having two arguments. Calculate second no as power of first.
import numpy as np

def pov(x,y):
    return x**y

pov=np.frompyfunc(pov,2,1)
print(pov(8,3))

dtype=type(pov)
print(dtype)

512
<class 'numpy.ufunc'>


In [72]:
# Create your own uni. function having one argument and display factorial

import numpy as np

def fact(x):
    for i in range(x):
        a=x*i
    print(a)
fact=np.frompyfunc(fact,1,1)
print(fact(4))

data_type=type(fact)
print(data_type)

12
None
<class 'numpy.ufunc'>


In [73]:
#Computation on Arrays-broadcasting, comparisons, Fancy indexing etc.

#comparison using '=='sign or array_equal(a,b)

import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.array([7,8])

print(np.array_equal(a,b))
print(np.array_equal(a,c))

print(np.setdiff1d(a,b))
print(np.intersect1d(a,b))
print(np.array_equiv(np.sort(a),np.sort(b)))

#array_equiv and array_equal have same functions..

False
False
[1]
[2 3]
False


In [74]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[1,2,3]])
print(np.array_equal(a,b))
print(np.array_equiv(np.sort(a),np.sort(b)))

False
True


In [75]:
#Broadcasting

import numpy as np

a=np.array([[1,2,3,4],[5,6,7,8],[4,7,3,9]])
b=np.array([2,4,6,7])

print("\n Matrix A: \n",a)

print("\n Matrix B: ",b)

c=a+b;
print("\nAddition: \n",c)


 Matrix A: 
 [[1 2 3 4]
 [5 6 7 8]
 [4 7 3 9]]

 Matrix B:  [2 4 6 7]

Addition: 
 [[ 3  6  9 11]
 [ 7 10 13 15]
 [ 6 11  9 16]]


In [76]:
#Fancy Indexing

import numpy as np
array1=np.array([1,2,3,4,5,6,7,8,9])

select_elements=array1[[1,2,5,7]]
print(select_elements)

[2 3 6 8]


In [77]:
#Fancy indexing to assign new values to specific elements

import numpy as np
array1=np.array([3,2,6,1,8,5,7,4])
indices=[1,3,6]
new_values=[10,20,30]
array1[indices]=new_values
print(array1)


[ 3 10  6 20  8  5 30  4]


Practice Questions


1.Write a program to add all the elements of 1D array.

In [7]:
import numpy as np

# Create a 1D numpy array
array = np.array([1, 2, 3, 4, 5])

# Add all elements of the array
total = np.sum(array)

# Display the result
print("Sum of all elements in the array:", total)


Sum of all elements in the array: 15


2. Write a program to accept any element from the user and search it in the array. Also show the position of it.

In [8]:
import numpy as np

# Create a numpy array
array = np.array([10, 20, 30, 40, 50])

# Accept an element from the user
element = int(input("Enter the element to search: "))

# Search for the element and get its position
position = np.where(array == element)

# Check if the element is found
if position[0].size > 0:
    print(f"Element {element} found at position(s): {position[0]}")
else:
    print(f"Element {element} not found in the array.")


Element 4 not found in the array.


3. Write a program addition of two arrays.

In [9]:
import numpy as np

# Create two numpy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Add the two arrays
result = array1 + array2

# Display the result
print("Sum of the two arrays:", result)


Sum of the two arrays: [6 6 6 6 6]


4. Write a program to add multiple elements (Range) into existing array.


In [10]:
import numpy as np

# Create an existing numpy array
existing_array = np.array([1, 2, 3, 4, 5])

# Define the range of elements to add (e.g., adding numbers from 6 to 10)
new_elements = np.arange(6, 11)  # Generates numbers from 6 to 10

# Add the new elements to the existing array
updated_array = np.concatenate((existing_array, new_elements))

# Display the updated array
print("Updated array:", updated_array)


Updated array: [ 1  2  3  4  5  6  7  8  9 10]


5. Write a program a 1D array and display all negative numbers.

In [11]:
import numpy as np

# Create a 1D numpy array
array = np.array([1, -2, 3, -4, 5, -6, 7, -8, 9])

# Display all negative numbers using boolean indexing
negative_numbers = array[array < 0]

# Display the result
print("Negative numbers in the array:", negative_numbers)


Negative numbers in the array: [-2 -4 -6 -8]


6. Write a program to create 1D array and display the count of negative numbers, positive numbers and zeros in the array.

In [6]:
import numpy as np

# Create a 1D numpy array
array = np.array([1, -2, 3, 0, -4, 5, 0, -6, 7, 0])

# Count the negative, positive, and zero numbers
negative_count = np.count_nonzero(array < 0)
positive_count = np.count_nonzero(array > 0)
zero_count = np.count_nonzero(array == 0)

# Display the counts
print(f"Negative numbers: {negative_count}")
print(f"Positive numbers: {positive_count}")
print(f"Zeroes: {zero_count}")


Negative numbers: 3
Positive numbers: 4
Zeroes: 3


7. Write a program to display the smallest number in the array.

In [12]:
import numpy as np

# Create a 1D numpy array
array = np.array([10, 2, 33, 4, 50, 6])

# Find the smallest number in the array
smallest_number = np.min(array)

# Display the result
print("The smallest number in the array is:", smallest_number)


The smallest number in the array is: 2


8. Write a program to display even numbers in the given array.

In [13]:
import numpy as np

# Create a 1D numpy array
array = np.array([10, 21, 32, 43, 54, 65, 76, 87, 98])

# Display even numbers using boolean indexing
even_numbers = array[array % 2 == 0]

# Display the result
print("Even numbers in the array:", even_numbers)


Even numbers in the array: [10 32 54 76 98]


9. Sorting example

In [16]:
import numpy as np

#set alias names for dtypes

dtypes= [('name','S10'),('grad_year',int),('cgpa',float)]

#Values to be put in the array

values=[('Chetana',2009,8.5),('Pooja',2019,9.5),('Arya',2010,7.5),('Talat',2009,9.5)]

#Creating array

arr= np.array(values,dtype=dtypes)
print(arr)

print("\n Array sorted by names: \n", np.sort(arr,order='name'))

print("\n Array sorted by graduation year and then cgpa: \n", np.sort(arr,order=['grad_year','cgpa']))

[(b'Chetana', 2009, 8.5) (b'Pooja', 2019, 9.5) (b'Arya', 2010, 7.5)
 (b'Talat', 2009, 9.5)]

 Array sorted by names: 
 [(b'Arya', 2010, 7.5) (b'Chetana', 2009, 8.5) (b'Pooja', 2019, 9.5)
 (b'Talat', 2009, 9.5)]

 Array sorted by graduation year and then cgpa: 
 [(b'Chetana', 2009, 8.5) (b'Talat', 2009, 9.5) (b'Arya', 2010, 7.5)
 (b'Pooja', 2019, 9.5)]
