1. Program to find maximum value and minimum value from the given matrix

In [6]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print(arr)

a=arr.min()
print("\n The Minimum value in the array is: ",a)


b=arr.max()
print("\n The Maximum value in the array is: ",b)

[[1 2 3]
 [4 5 6]]

 The Minimum value in the array is:  1

 The Maximum value in the array is:  6


2. Program to perform following operations on the given matrix 
a. Find the number of rows and columns of a given matrix using NumPy
b. Find the sum of values in a matrix

In [1]:
import numpy as np

# Sample matrix
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

# a. Find the number of rows and columns of the given matrix
rows, cols = matrix.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {cols}")

# b. Find the sum of values in the matrix
matrix_sum = np.sum(matrix)
print(f"Sum of values in the matrix: {matrix_sum}")


Number of rows: 3
Number of columns: 3
Sum of values in the matrix: 45


3. Program to perform following operations on 3x3 matrix:
a. addition of two matrices
b. Subtraction of two matrices
c. Multiplication of two matrices

In [7]:
import numpy as np

# Define two 3x3 matrices
matrix1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

matrix2 = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])

result = np.zeros((3, 3), dtype=int)

# a. Addition of two matrices
addition_result = np.add(matrix1, matrix2)
print("Addition of two matrices:")
print(addition_result)

# b. Subtraction of two matrices
subtraction_result = np.subtract(matrix1, matrix2)
print("\nSubtraction of two matrices:")
print(subtraction_result)

# c. Multiplication of two matrices
for i in range(3):  # Loop through rows of matrix1
    for j in range(3):  # Loop through columns of matrix2
        result[i][j] = 0  # Initialize the result element at position (i, j)
        for k in range(3):  # Perform the dot product for each element
            result[i][j] += matrix1[i][k] * matrix2[k][j]

print("\nMatrix multiplication (row by column) in i, j form:")
print(result)


Addition of two matrices:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of two matrices:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Matrix multiplication (row by column) in i, j form:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


4. Program to perform following operations on 1D array
a. Count the frequency of unique values in NumPy array?
b. Convert the matrix into a list
c. Replace negative value with zero in numpy array

In [13]:
import numpy as np

# Create a 1D NumPy array
array = np.array([1, -2, 3, -2, 4, 5, -2, 1])

# a. Count the frequency of unique values using np.unique()
unique, counts = np.unique(array, return_counts=True)

# Directly print the result as a dictionary
frequency = dict(zip(unique.tolist(), counts.tolist()))  # Convert to list to avoid np.int64
print("Frequency of unique values:", frequency)

# b. Convert the NumPy array into a list
array_list = array.tolist()
print("\nArray converted to list:", array_list)

# c. Replace negative values with zero in the NumPy array
array[array < 0] = 0
print("\nArray with negative values replaced by zero:", array)


Frequency of unique values: {-2: 3, 1: 2, 3: 1, 4: 1, 5: 1}

Array converted to list: [1, -2, 3, -2, 4, 5, -2, 1]

Array with negative values replaced by zero: [1 0 3 0 4 5 0 1]


5. Program to perform statistical operations on the given array.
a. Compute the median of the flattened NumPy array
b. Find Mean of Numpy Array
c. Compute the variance of the NumPy array
d. Compute the standard deviation of the NumPy array

In [14]:
import numpy as np

# Create a NumPy array
array = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

# a. Compute the median of the flattened NumPy array
flattened_array = array.flatten()  # Flatten the array to 1D
median_value = np.median(flattened_array)
print("Median of flattened array:", median_value)

# b. Find the mean of the NumPy array
mean_value = np.mean(array)
print("\nMean of the array:", mean_value)

# c. Compute the variance of the NumPy array
variance_value = np.var(array)
print("\nVariance of the array:", variance_value)

# d. Compute the standard deviation of the NumPy array
std_deviation_value = np.std(array)
print("\nStandard deviation of the array:", std_deviation_value)


Median of flattened array: 5.0

Mean of the array: 5.0

Variance of the array: 6.666666666666667

Standard deviation of the array: 2.581988897471611


6. Create a 5X2 integer array from a range between 100 to 200 such that the
difference between each element is 10

In [18]:
import numpy as np

# Create a range from 100 to 200 with a step of 10, generating exactly 10 elements
array = np.arange(100, 201, 10)[:10]  # Take the first 10 elements

# Reshape the array to 5x2
reshaped_array = array.reshape(5, 2)

print("5x2 array with values between 100 and 200, step 10:")
print(reshaped_array)



5x2 array with values between 100 and 200, step 10:
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


7. Following is the provided numPy array. Return array of item by taking
the third column from all rows
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
output: [33 66 99

In [20]:
import numpy as np

# Provided NumPy array
sampleArray = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])

# Extract the third column (index 2) from all rows
third_column = sampleArray[:, 2]

print("Third column from all rows:", third_column)


Third column from all rows: [33 66 99]
